version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  php-app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: php-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app 

volumes:
  postgres-data:
